### ISSUE TITLE
Accessing secured Kafka topic using zipkin-storage-kafka.

### ISSUE THREAD

**Issue by Rietty** [openzipkin-contrib/zipkin-storage-kafka#69]
I have a secured kafka topic that I would like to access with this software, is it possible to do so given a krb5.conf/tab and jaas file?

If so how can I accomplish this?

Thank you

**Comment by jeqo** [comment]
Hi @Rietty, configuration overrides work [similar as in Zipkin ](https://github.com/openzipkin/zipkin/tree/master/zipkin-server#other-kafka-consumer-properties). In this case it would be similar to `-Dzipkin.storage.kafka.overrides.security.protocol=SASL_PLAINTEXT` etc.

Let me know if it works in your environment.
